"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class data_from_ifm(object):
    __slots__ = ["num_fires", "current_HRR"]

    def __init__(self):
        self.num_fires = 0
        self.current_HRR = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(data_from_ifm._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">id", self.num_fires, self.current_HRR))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != data_from_ifm._get_packed_fingerprint():
            raise ValueError("Decode error")
        return data_from_ifm._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = data_from_ifm()
        self.num_fires, self.current_HRR = struct.unpack(">id", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if data_from_ifm in parents: return 0
        tmphash = (0xba24b9e1d72b389f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if data_from_ifm._packed_fingerprint is None:
            data_from_ifm._packed_fingerprint = struct.pack(">Q", data_from_ifm._get_hash_recursive([]))
        return data_from_ifm._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

