"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class edm(object):
    __slots__ = ["time", "temp", "flux"]

    def __init__(self):
        self.time = 0.0
        self.temp = 0.0
        self.flux = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(edm._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.time, self.temp, self.flux))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != edm._get_packed_fingerprint():
            raise ValueError("Decode error")
        return edm._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = edm()
        self.time, self.temp, self.flux = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if edm in parents: return 0
        tmphash = (0x4ed689a69b72abb0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if edm._packed_fingerprint is None:
            edm._packed_fingerprint = struct.pack(">Q", edm._get_hash_recursive([]))
        return edm._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

