/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __send_to_edm_data_to_edm_hpp__
#define __send_to_edm_data_to_edm_hpp__

#include <vector>

namespace send_to_edm
{

class data_to_edm
{
    public:
        double     time_stamp;

        int32_t    num_rooms;

        std::vector< double > temperature;

        std::vector< double > O2_conc;

        std::vector< double > CO_conc;

        std::vector< double > CO2_conc;

        std::vector< double > HCN_conc;

        std::vector< double > heat_flux;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "data_to_edm"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int data_to_edm::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int data_to_edm::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int data_to_edm::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t data_to_edm::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* data_to_edm::getTypeName()
{
    return "data_to_edm";
}

int data_to_edm::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->time_stamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_rooms, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_rooms > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->temperature[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->O2_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->CO_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->CO2_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->HCN_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->heat_flux[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int data_to_edm::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->time_stamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_rooms, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_rooms) {
        this->temperature.resize(this->num_rooms);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->temperature[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms) {
        this->O2_conc.resize(this->num_rooms);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->O2_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms) {
        this->CO_conc.resize(this->num_rooms);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->CO_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms) {
        this->CO2_conc.resize(this->num_rooms);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->CO2_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms) {
        this->HCN_conc.resize(this->num_rooms);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->HCN_conc[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_rooms) {
        this->heat_flux.resize(this->num_rooms);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->heat_flux[0], this->num_rooms);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int data_to_edm::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->num_rooms);
    enc_size += __double_encoded_array_size(NULL, this->num_rooms);
    enc_size += __double_encoded_array_size(NULL, this->num_rooms);
    enc_size += __double_encoded_array_size(NULL, this->num_rooms);
    enc_size += __double_encoded_array_size(NULL, this->num_rooms);
    enc_size += __double_encoded_array_size(NULL, this->num_rooms);
    return enc_size;
}

uint64_t data_to_edm::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x17f7de75b338b8a9LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
